### ISSUE TITLE
Im getting error

### ISSUE THREAD

**Issue by PthAtomic** [Knakiri/gt-apk-stealer#2]
Im getting error with import kotlin.io.FilesKt;
import kotlin.jvm.internal.Intrinsics;
So is there any fix? + the new website was good

**Comment by Knakiri** [comment]
download the jar: https://jar-download.com/artifacts/org.jetbrains.kotlin/kotlin-stdlib/0.7.86/source-code/kotlin/io/Files.kt
then import it 
for more help join discord server: https://discord.gg/5gRmNAbz2m

**Comment by Knakiri** [comment]
the website had some issues i fixed it now it should probably work now i already tested it
